In [1]:
import astrolights

Initilization module astrolights


In [2]:
import cv2
import os
import re
import numpy as np

In [3]:
#import importlib
#importlib.reload(astrolights)

In [4]:
tmpDir='/mnt/data/Photos/Repository/tmp'
tmpGeneratedFiles = []
regenerateOffset = False
regenerateFlat = True
regenerateDark = True

In [5]:
imagesDirectory = '/mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9'
categories = astrolights.files.categorifyRawImages(imagesDirectory)

flatDirectory = '/mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9'
categoriesFlat = astrolights.files.categorifyRawImages(flatDirectory)

darkDirectory = '/mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9'
categoriesDark = astrolights.files.categorifyRawImages(darkDirectory)

offsetDirectory = '/mnt/data/Photos/Repository/2018/Offset_1600iso'
categoriesOffset = astrolights.files.categorifyRawImages(offsetDirectory)

In [6]:
offsetList = categoriesOffset['OFFSET']
darkList = categoriesDark['DARK']
flatList = categoriesFlat['FLAT']
imageList = categories['LIGHT']

In [7]:
imageList

['/mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3J9.CR2',
 '/mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3JK.CR2',
 '/mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3J7.CR2',
 '/mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3JY.CR2',
 '/mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3JV.CR2',
 '/mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3J4.CR2',
 '/mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3JS.CR2',
 '/mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3JR.CR2',
 '/mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3J3.CR2',
 '/mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3JH.CR2']

# Generating master offset

The generation of the master offset is just a median of all offset image

In [8]:
if regenerateOffset:
    masterOffset = astrolights.processImages.calculateMedianFromFiles(offsetList)
    masterOffset = masterOffset.astype(np.uint16, copy=False)
    cv2.imwrite(tmpDir + '/' + "masterOffset.pgm", masterOffset)
else:
    try:
        masterOffset = cv2.imread(tmpDir + '/' + "masterOffset.pgm", flags=cv2.IMREAD_GRAYSCALE | cv2.IMREAD_IGNORE_ORIENTATION | cv2.IMREAD_ANYDEPTH)
    except:
        print('File: {} for the Master Offset not found.'.format(tmpDir + '/' + "masterOffset.pgm"))

In [9]:
masterOffset

array([[ 26,   0,  48, ...,   0,  21,  48],
       [105,  69,  45, ...,  60,   0,  32],
       [  0,   0,   0, ...,   0,  16,   0],
       ..., 
       [ 26,   0,   0, ...,   0,   0,   0],
       [ 97,   5,  75, ...,   5,  75,  85],
       [  0,   0,   5, ...,  53,  26,  80]], dtype=uint16)

# Generating master Dark

In [10]:
if regenerateDark:
    masterDark = astrolights.processImages.calculateMedianFromFiles(darkList)
    masterDark = masterDark.astype(np.uint16, copy=False)
    cv2.imwrite(tmpDir + '/' + "masterDark.pgm", masterDark)
else:
    try:
        masterDark = cv2.imread(tmpDir + '/' + "masterDark.pgm", flags=cv2.IMREAD_GRAYSCALE | cv2.IMREAD_IGNORE_ORIENTATION | cv2.IMREAD_ANYDEPTH)
    except:
        print('File: {} for the Master Dark not found.'.format(tmpDir + '/' + "masterDark.pgm"))

dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3DZ.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z32S.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z32J.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3DC.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z32P.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3D8.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3D6.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z322.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z325.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z32D.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8

In [11]:
masterDark

array([[ 523,    0,    0, ...,  102,    0,    0],
       [  32,    0,    0, ...,    0,    0,   15],
       [5572,    0,  537, ...,    0,    0, 4055],
       ..., 
       [   0,    0,    0, ...,    0,    0,   59],
       [   0,    0,    0, ...,    0,    0,    0],
       [ 738,  171,    0, ...,    0,    0,  418]], dtype=uint16)

# Generating master Flat

In [12]:
if regenerateFlat:
    masterFlat = astrolights.processImages.calculateMedianFromFiles(flatList)
    masterFlat = masterFlat.astype(np.uint16, copy=False)
    cv2.imwrite(tmpDir + '/' + "masterFlat.pgm", masterFlat)
else:
    try:
        masterFlat = cv2.imread(tmpDir + '/' + "masterFlat.pgm", flags=cv2.IMREAD_GRAYSCALE | cv2.IMREAD_IGNORE_ORIENTATION | cv2.IMREAD_ANYDEPTH)
    except:
        print('File: {} for the Master Flat not found.'.format(tmpDir + '/' + "masterFlat.pgm"))

dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3JD.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z329.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z32C.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z32L.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z32A.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z32U.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z32Z.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z327.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z328.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z32F.CR2
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8

In [13]:
meanFlat = np.mean(masterFlat)

In [14]:
masterFlat

array([[18295, 12932, 19191, ..., 14049, 21712, 14428],
       [13627, 11421, 13405, ..., 12409, 14971, 13183],
       [19192, 13020, 17598, ..., 14909, 22021, 15059],
       ..., 
       [18147, 12673, 17999, ..., 14029, 21914, 14560],
       [12832, 10778, 12448, ..., 13040, 14930, 12901],
       [18837, 12922, 18026, ..., 14491, 21009, 14694]], dtype=uint16)

In [15]:
meanFlat

21112.80730865529

# Calculate images

In [16]:
#correctedImages = astrolights.processImages.correctImages(imageList, masterOffset, masterDark, masterFlat)

In [17]:
i=0
for image in imageList:
    correctedImage = astrolights.processImages.correctImages(image, masterOffset, masterDark, masterFlat)
    #correctedImage = correctedImage/correctedImage.max()*65535
    
    # Correction Gamma
    #print('Ajust Gamma')
    correctedImage = correctedImage.astype(np.float64, copy=False) 
    print(correctedImage.min())
    print(correctedImage.max())
    
    correctedImage -= correctedImage.min()
    correctedImage = (correctedImage / correctedImage.max()) * 65535
    print(correctedImage.min())
    print(correctedImage.max())
    correctedImage = correctedImage.astype(np.uint16, copy=False)
    print(correctedImage.shape)
    BGR_image = cv2.cvtColor(correctedImage, cv2.COLOR_BayerBG2BGR_EA)

    bitDepth = 2.0**16
    BGR_image = np.power(BGR_image/bitDepth, 1/2.1)*bitDepth
    
    #Correction of the white balance
    #print('Ajust White balance')
    #BGR_image = astrolights.histogram.ajustWhiteBalance(BGR_image)
    
    #Normalization of the histogram
    print('Normalize the histogram')
    BGR_image = astrolights.histogram.normalizeHistogram(BGR_image, sigma1=3, sigma2=10)
    
    BGR_image = BGR_image.astype(np.uint16, copy=False)
    i += 1
    print("Writing: Corrected_{:04d}.png".format(i))
    cv2.imwrite(tmpDir + '/' + "Corrected_{:04d}.png".format(i), BGR_image)


dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3J9.CR2
-53633.9062172
121693.062222
0.0
65535.0
(3465, 5202)
Normalize the histogram
Writing: Corrected_0001.png
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3JK.CR2
-47950.7588991
125249.192267
0.0
65535.0
(3465, 5202)
Normalize the histogram
Writing: Corrected_0002.png
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3J7.CR2
-52794.0037081
119815.364303
0.0
65535.0
(3465, 5202)
Normalize the histogram
Writing: Corrected_0003.png
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3JY.CR2
-50471.3716477
121693.062222
0.0
65535.0
(3465, 5202)
Normalize the histogram
Writing: Corrected_0004.png
dcraw -d -4 /mnt/data/Photos/Repository/2018/08-AstroReise-La_Palma-Astro9/JPB-8F7_Z3JV.CR2
-50847.7532178
123296.010245
0.0
65535.0
(3465, 5202)
Normalize the histogram
Writing: Corrected_0005.png
dcraw -d -

# Aligns images

Hugin is used to align the generated images:

    align_image_stack -v --gpu -a Aligned_ Corrected_*.png

# Add aligned Images

In [18]:
alignedImages = astrolights.files.listAllFileinDir(tmpDir, '^Aligned_.*')

In [19]:
alignedImages

['/mnt/data/Photos/Repository/tmp/Aligned_0008.tif',
 '/mnt/data/Photos/Repository/tmp/Aligned_0006.tif',
 '/mnt/data/Photos/Repository/tmp/Aligned_0007.tif',
 '/mnt/data/Photos/Repository/tmp/Aligned_0009.tif',
 '/mnt/data/Photos/Repository/tmp/Aligned_0003.tif',
 '/mnt/data/Photos/Repository/tmp/Aligned_0001.tif',
 '/mnt/data/Photos/Repository/tmp/Aligned_0005.tif',
 '/mnt/data/Photos/Repository/tmp/Aligned_0004.tif',
 '/mnt/data/Photos/Repository/tmp/Aligned_0002.tif',
 '/mnt/data/Photos/Repository/tmp/Aligned_0000.tif']

In [20]:
image = cv2.imread(alignedImages.pop(0), cv2.IMREAD_IGNORE_ORIENTATION | cv2.IMREAD_ANYDEPTH | cv2.IMREAD_ANYCOLOR)
image = image.astype(np.float64, copy=False)

imageCpt = 0
for i in alignedImages:
    print('Adding {}'.format(i))
    image += cv2.imread(i, cv2.IMREAD_IGNORE_ORIENTATION | cv2.IMREAD_ANYDEPTH | cv2.IMREAD_ANYCOLOR)
    imageCpt += 1

image = image / imageCpt


Adding /mnt/data/Photos/Repository/tmp/Aligned_0006.tif
Adding /mnt/data/Photos/Repository/tmp/Aligned_0007.tif
Adding /mnt/data/Photos/Repository/tmp/Aligned_0009.tif
Adding /mnt/data/Photos/Repository/tmp/Aligned_0003.tif
Adding /mnt/data/Photos/Repository/tmp/Aligned_0001.tif
Adding /mnt/data/Photos/Repository/tmp/Aligned_0005.tif
Adding /mnt/data/Photos/Repository/tmp/Aligned_0004.tif
Adding /mnt/data/Photos/Repository/tmp/Aligned_0002.tif
Adding /mnt/data/Photos/Repository/tmp/Aligned_0000.tif


In [21]:
image2 = image - image.min()
image2 = (image2 / image2.max()) * 65535.0

In [22]:
image2.max()

65535.0

In [23]:
# Gamma ajustement
image2 = image2.astype(np.float32, copy=False) 
bitDepth = 2.0**16
image2 = np.power(image2/bitDepth, 1/2.1)*bitDepth

In [24]:
print('Ajust White balance')
image3 = astrolights.histogram.ajustWhiteBalance(image2)
    
#Normalization of the histogram
#print('Normalize the histogram')
#image2 = astrolights.histogram.normalizeHistogram(image2)

Ajust White balance


In [25]:
#image2 = astrolights.histogram.normalizeHistogram(image)

In [26]:
image2 = image2.astype(np.uint16, copy=False)

In [27]:
cv2.imwrite(tmpDir + '/' + 'image.tif', image2)

True

In [ ]:
# remove files: RAWoffsetFiles, RAWdarkFiles, RAWflatFiles and RAWimageFiles